"""empty message

Revision ID: 136b6de44d2d
Revises: 724da492dbe8
Create Date: 2019-11-21 14:49:06.484071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136b6de44d2d'
down_revision = '724da492dbe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool')
    op.drop_table('tec')
    # ### end Alembic commands ###
