"""empty message

Revision ID: 1b17967378b0
Revises: 724da492dbe8
Create Date: 2019-11-21 23:16:26.900012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b17967378b0'
down_revision = '724da492dbe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_group_withDPGPAS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('dpgpas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dpgpas_id'], ['DPGPAS.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_group_withDSPGPGC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('dspgpgc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dspgpgc_id'], ['DSPGPGC.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_group_withDSPGPGC')
    op.drop_table('process_group_withDPGPAS')
    # ### end Alembic commands ###
