"""empty message

Revision ID: 20f5c179c9bd
Revises: 8b2bfa337be4
Create Date: 2019-11-22 03:58:35.131593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f5c179c9bd'
down_revision = '8b2bfa337be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_group_with_dspgpg_c2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('dspgpgc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dspgpgc_id'], ['DSPGPGC.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.drop_table('process_group_withDSPGPGC')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_group_withDSPGPGC',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('dspgpgc_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=140), nullable=True),
    sa.ForeignKeyConstraint(['dspgpgc_id'], ['DSPGPGC.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('process_group_with_dspgpg_c2')
    # ### end Alembic commands ###
