"""empty message

Revision ID: 2643cc115783
Revises: b9d1b111201e
Create Date: 2019-11-21 15:05:04.662533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2643cc115783'
down_revision = 'b9d1b111201e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tec', 'process_group', ['process_id'], ['id'])
    op.add_column('tool', sa.Column('process_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tool', 'process_group', ['process_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool', type_='foreignkey')
    op.drop_column('tool', 'process_id')
    op.drop_constraint(None, 'tec', type_='foreignkey')
    # ### end Alembic commands ###
