"""users table

Revision ID: 2a71358d2fac
Revises: 3fc860009008
Create Date: 2019-10-21 20:26:12.814211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a71358d2fac'
down_revision = '3fc860009008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rank', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rank')
    # ### end Alembic commands ###
