"""empty message

Revision ID: 44ec8b37250c
Revises: 009f57d3e2b9
Create Date: 2019-12-03 04:55:54.058605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ec8b37250c'
down_revision = '009f57d3e2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_activityDPGPAS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('dpgpas_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activityDPGPAS.id'], ),
    sa.ForeignKeyConstraint(['dpgpas_id'], ['process_group_with_dpgpa_s2.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_activityDSPGPGC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('dspgpgc_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activityDSPGPGC.id'], ),
    sa.ForeignKeyConstraint(['dspgpgc_id'], ['process_group_with_dspgpg_c2.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_activityDSPGPGC')
    op.drop_table('task_activityDPGPAS')
    # ### end Alembic commands ###
