"""empty message

Revision ID: 5a4dad244499
Revises: 20f5c179c9bd
Create Date: 2019-11-22 04:00:42.083486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4dad244499'
down_revision = '20f5c179c9bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_group_with_dpgpa_s2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('dpgpas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dpgpas_id'], ['DPGPAS.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.drop_table('process_group_withDPGPAS')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_group_withDPGPAS',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('dpgpas_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['dpgpas_id'], ['DPGPAS.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('process_group_with_dpgpa_s2')
    # ### end Alembic commands ###
