"""empty message

Revision ID: 8b2bfa337be4
Revises: 2e933c1015b2
Create Date: 2019-11-22 03:52:42.313158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2bfa337be4'
down_revision = '2e933c1015b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_group_withDPGPAS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('dpgpas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dpgpas_id'], ['DPGPAS.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'process_group_withDSPGPGC', ['description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'process_group_withDSPGPGC', type_='unique')
    op.drop_table('process_group_withDPGPAS')
    # ### end Alembic commands ###
