"""DPGPAS table

Revision ID: 969ef26d604e
Revises: 2a71358d2fac
Create Date: 2019-10-22 10:12:51.194737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969ef26d604e'
down_revision = '2a71358d2fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DPGPAS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('DSPGPGC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DSPGPGC')
    op.drop_table('DPGPAS')
    # ### end Alembic commands ###
